#!/usr/bin/env ruby
require './init.rb'

puts ARGV[0]
if version = ARGV[0]
  puts "Updating IPA version from #{Settings.ipa_version} to #{version}"
  Settings.ipa_version = version
else
  puts "Current IPA Version: #{Settings.ipa_version}"
end